language: csharp
mono: none
dotnet: 2.2
sudo: required
dist: xenial
solution: DoorControlSystem.sln
before_install:
  - pip install --user codecov
  - dotnet tool install --global coverlet.console
after_success:
  - coverlet test/DoorControlSystem.Unit.Test/bin/Debug/netcoreapp2.2/DoorControlSystem.Unit.Test.dll --target="dotnet" --targetargs "test test/DoorControlSystem.Unit.Test --no-build" -f lcov
  - codecov --file coverage.info --disable search
script:
  - dotnet restore
  - dotnet build
  - dotnet test 
  - if [ $TRAVIS_BRANCH == "master" ]; then
      curl -s https://codecov.io/bash > codecov
      chmod +x codecov
      ./codecov -f "coverage.info" -t $CODECOV_TOKEN
    else
      echo "Skipped"
    fi
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
