language: csharp
mono: none
dotnet: 2.2
sudo: required
dist: xenial
solution: DoorControlSystem.sln
before_install:
  - pip install --user codecov
  - dotnet add test/DoorControlSystem.Unit.Test package coverlet.msbuild
script:
  - dotnet restore
  - dotnet build
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"lcov\"
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "test/DoorControlSystem.Unit.Test/coverage.info" -t 131fde5b-aa7b-4290-b2fa-34322281cd29

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
